# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaPPi76JR6IGIAj-CZCsp5fDPvW6vFXI?resourcekey=0-x3fwmKp68vFyB_tEExY8AA
"""



#bart simpson program.  Display 1000 times message.  Include in display console 1. message... to 1000. message
i = 0
while i < 1000:
  i += 1
  print(f"{i}. I will not get hit in the face at the gym!")

"#display hello world to the console
print("hello world!")